<?php
/**
 * @file
 * Code for the Lightroom feature.
 */

include_once 'lightroom.features.inc';

/**
 * Implements hook_services_resources()
 */
function lightroom_services_resources() {
  $resource = array(
    'collection' => array(
      'actions' => array(
        'types' => array(
          'help'   => t('Returns info about collection content types'),
          'access callback' => 'lightroom_node_types_access',
          'callback' => 'lightroom_node_types',
        )
      )
    )
  );
  return $resource;
}

function lightroom_node_types_access() {

  // Check if there are any node_types they can access
  // Basically, get the node types here, cache them for later
  $types = lightroom_node_types();
  return !empty($types);

}

function lightroom_node_types() {

  static $types;

  if (!isset($types)) {

    $types = array();

    // Get node types with field_collection_images
    $instances = field_read_instances(array('entity_type' => 'node', 'field_name' => 'field_collection_images'));
    foreach ($instances as $instance) {
      $bundle = $instance['bundle'];
      // Check that this user has permission to create this type of node
      if (node_access('create', $bundle)) {
        $types[] = node_type_get_type($bundle);
      }
    }
  }

  return $types;

}